### ISSUE TITLE
Checkpointing and modifying the disk

### ISSUE THREAD

**Issue by andrewzigerelli** [cirosantilli2/gem5-issues#23]
Hi Ciro,

Do you have any idea how to force disk changes to be loaded by gem without recheckpointing?

When I change the disk in qemu and reload my checkpoint, I don't see new files. Further, if I recompile a file in qemu (need to do this for now, hope to make buildroot work later), my binaries become 0 bytes in gem.
I'm using a raw disk with ubuntu.

I tried:
```
# sync
# echo 3 > /proc/sys/vm/drop_caches
```
from telnet, but cannot force gem to re-read from disk.
Thanks
Andrew

**Comment by cirosantilli2** [comment]
Hi Andrew,

When I use QEMU with an ext4 filesystem (no initrd) and no `snapshot` option, it did write to disk.

I've just retested: https://github.com/cirosantilli/linux-kernel-module-cheat/tree/550897ce1766e8df0b4ffcfdc17206f788d9f67f#disk-persistency now and it still worked.

**Comment by andrewzigerelli** [comment]
Thank you so much! I needed to remove snapshot..
